apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendjava-java-deployment
  labels:
    app: frontendjava-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendjava-java
  template:
    metadata:
      labels:
        app: frontendjava-java 
    spec:
      containers:
      - name: frontendjava-javaserver
        image: madhublue01/frontendjava:latest
        ports:
        - containerPort: 3000
