apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendjava-java-deployment
  labels:
    app: frontendjava-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendjava-java
  template:
    metadata:
      labels:
        app: frontendjava-java
    spec:
      containers:
      - name: frontendjava-javaserver
        image: madhublue01/frontendjava:latest
        ports:
        - containerPort: 8082
        
        
---



apiVersion: v1
kind: Service
metadata:
  name: frontendjava-java-service
spec:
  selector:
    app: frontendjava-java
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8082
    nodePort: 30082
